### ISSUE TITLE
About us page

### ISSUE THREAD

**Issue by jvl4422** [cisc-322/cisc-322.github.io#3]
About us / contact us page :D it must have all of our names, emails and roles. It would also be nice if it links to all of our GitHubs and also nice if we could do headshots (but also I get it if that is a lot of work).

**Comment by Hashir103** [comment]
@jvl4422 do we want to use our own headshots? i can put placeholder headshots in the meantime.

rn i have it planned like this:

- headshot at top of card
- name
- role
- email
- hyper link to indiivdual github page

im lowkey thinking of adding a modal for the extra info (role, email, github) so that the page doesn't get oversaturated, but ill see depending on the style we decide on

**Comment by jvl4422** [comment]
I think using our own headshots would be nice, but a placeholder is good until we pick them! For the hyperlink we could probably just have either the GitHub logo and or make it link to our names. In regards to the style, @anishkabarran would be able to speak on that best, though I think she's probably leaning toward no modal

**Comment by Hashir103** [comment]
@jvl4422 anything else we're looking for? otherwise i can close this issue

**Comment by jvl4422** [comment]
The only small edit I have is to lowercase the v in my last name hahhah but I'll just do that along with the landing page or something
